### ISSUE TITLE
Bug Report: Libraries Conflict Causing Issues

### ISSUE THREAD

**Issue by Muli121** [Muli121/Portfolio-Template#1]
There are conflicts between the libraries used in the project, resulting in the index page failing to render correctly. This issue leads to [briefly describe the symptom, e.g., missing elements, broken layout, etc.].

Steps to Reproduce:

Clone the repository: git clone https://github.com/username/repo-name
Navigate to the project directory: cd repo-name
Install dependencies: npm install
Start the development server: npm start
Open the index page in the browser: [insert URL, e.g., http://localhost:3000]
Observe the issues on the page.
Expected Result: The index page should render correctly with all elements displayed as intended.

Actual Result: The index page shows [describe the issues, e.g., "missing images," "broken layout," "JavaScript errors in the console," etc.]. The following error messages were logged in the console:

[Insert any relevant error messages or logs here]
Libraries Involved:

[List the libraries that may be causing the conflict, e.g., library1@version, library2@version]
Severity: [e.g., Critical, Major, Minor]

Additional Notes:

[Mention any specific combinations of libraries that lead to the issue, or if the problem occurs only with specific versions.]
[If applicable, mention any temporary fixes or workarounds you’ve tried.]

**Comment by Flamur112** [comment]
Hi, I would like to work on this please

**Comment by Muli121** [comment]
I just assigned you 👍

**Comment by Muli121** [comment]
Done
