### ISSUE TITLE
Footer Not Rendering Properly on Webpage

### ISSUE THREAD

**Issue by Muli121** [Muli121/Portfolio-Template#2]
The footer on the webpage does not render properly, resulting in an unappealing layout. The elements are misaligned, and the styling does not match the overall design of the website.
Steps to Reproduce:

Navigate to the webpage URL (e.g., http://example.com).
Scroll down to the footer section.
Observe the layout and styling of the footer elements.
Expected Result: The footer should display consistently with the website's design, including properly aligned elements, appropriate font sizes, and background colors.

Actual Result: The footer appears [describe the issues, e.g., "misaligned," "text overlapping," "background color incorrect," etc.]. The specific issues observed are:

[List specific problems, e.g., "text is too small," "links are not spaced correctly," "background color doesn't match the theme."]
Screenshots/Attachments: [Attach any relevant screenshots that illustrate the footer design issue.]

Severity: [e.g., Minor, Major]

Additional Notes:

[Mention any specific devices or browsers where the issue is more pronounced, if applicable.]
[If possible, provide CSS or design specifications that should be followed.]

**Comment by Flamur112** [comment]
I would like to be assigned this issue please

**Comment by Muli121** [comment]
Thank you for contributing!!

**Comment by Flamur112** [comment]
Your Welcome!
