### ISSUE TITLE
Header Not Rendering Properly on Webpage

### ISSUE THREAD

**Issue by Muli121** [Muli121/Portfolio-Template#3]
The header on the webpage does not render correctly, leading to a poor user experience. Elements within the header are misaligned or not styled according to the website's design specifications.
Steps to Reproduce:

Navigate to the webpage URL (e.g., http://example.com).
Observe the header section at the top of the page.
Note any misalignments or styling issues.
Expected Result: The header should display consistently with the website's design, including correctly aligned elements, appropriate font sizes, and colors that match the overall theme.

Actual Result: The header appears [describe the issues, e.g., "misaligned," "text overlapping," "logo not displayed correctly," etc.]. The specific issues observed are:

[List specific problems, e.g., "navigation links are not spaced evenly," "header background color is incorrect," "logo is distorted," etc.]
Screenshots/Attachments: [Attach any relevant screenshots that illustrate the header design issue.]

Severity: [e.g., Minor, Major]

Additional Notes:

[Mention any specific devices or browsers where the issue is more pronounced, if applicable.]
[If possible, provide CSS or design specifications that should be followed.]

**Comment by Flamur112** [comment]
If i can be assigned this issued.
**Thanks!**

**Comment by Muli121** [comment]
Thank you for contributing!!
I appreciate the hard work!!
I just opened this account not expecting this!! THANKS!

**Comment by Flamur112** [comment]
Hahahaha no problem
