### ISSUE TITLE
Request to Create a "Profiles" Page

### ISSUE THREAD

**Issue by Muli121** [Muli121/Portfolio-Template#4]
Description: I would like to request the creation of a new page titled "Profiles." This page will serve as a dedicated section for displaying user profiles, allowing users to view and manage their information.

Use Case: The Profiles page will be useful for:

Displaying user-specific information, such as profile pictures, bios, and contact details.
Allowing users to edit their profiles and manage their settings.
Providing a central location for users to view other users’ profiles and connect with them.
Proposed Features:

User Profile Display:

Show the user’s profile picture.
Include editable fields for user information (e.g., name, email, bio).
Display links to the user’s posts or contributions.
Edit Profile Functionality:

Allow users to update their profile information.
Implement a "Save" button to confirm changes.
User Search/Filter:

Implement a search bar to find other users by name or criteria.
Optionally, provide filters to narrow down profiles based on categories or interests.
Design Considerations:

The layout should be consistent with the existing design of the website.
Ensure mobile responsiveness for a better user experience on different devices.
Acceptance Criteria:

The Profiles page should be accessible from the main navigation menu.
The page should load quickly and display all relevant user information.
Users should be able to edit and save their profiles without errors.
Additional Notes:

[Any other relevant information or suggestions regarding the implementation of this feature.]
[Mention if there are any similar pages or features that can serve as a reference.]

**Comment by Flamur112** [comment]
I can help create this and fix the issues

**Comment by Muli121** [comment]
Thank you for contributing!!
I appreciate the hard work!!
I just opened this account not expecting this!! **THANKS!**
@Flamur112 ❤️
